#!/bin/bash



run() {

	docker run --detach --network="yaml_default" \
	  --link ccsdk_db_container:dbhost --link ccsdk_db_container:sdnctldb01 --link ccsdk_db_container:sdnctldb02 \
	  --publish 8181:8181 \
	  --publish 8185:8185 \
	  --publish 8085:8085 \
	  --publish 9200:9200 \
	  --env MYSQL_ROOT_PASSWORD=openECOMP1.0 \
	  --env SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties \
	  --name sdnr \
	onap/ccsdk-odlsli-image:latest
}

cli() {
	docker exec -t -i sdnr /bin/bash -c 'TERM=xterm exec /bin/bash'
}


echo "Docker onap helper"

case "$1" in
     "") 
	echo "Run docker image sdnr and attach to cli"
        docker stop sdnr
        docker rm sdnr
        run
        cli
        ;;
     e)
        echo "Attach to cli"
        cli
	;;
esac
